# Generated by Django 2.2.12 on 2020-04-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=130)),
                ('identifier', models.CharField(max_length=30)),
            ],
        ),
    ]
